name: Build MacOS app

on: workflow_dispatch

env:
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
  NOTARIZE_TOOL: notarytool
  APPLE_ID: ${{ secrets.APPLE_ID }}
  APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
  APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}

jobs:
  release-macos-application:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: "favia-ai/desktop"
      - uses: actions/setup-node@v3
        with:
          node-version: "21.x"
          cache: "yarn"

      - name: Install project dependencies
        run: yarn install

      - uses: apple-actions/import-codesign-certs@v2
        with:
          p12-file-base64: ${{ secrets.CERTIFICATES_P12 }}
          p12-password: ${{ secrets.CERTIFICATES_P12_PASSWORD }}

      - name: 👷‍♂️ Building and Publishing MacOS application
        run: yarn run publish
